resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/config/routes.rb
GalleryApp::Application.routes.draw do
  root :to => "galleries#index"

  resources :galleries
  resources :paintings

end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :address, :name
  has_many :paintings
end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :artist, :description, :gallery_id, :price, :title, :image
  belongs_to :gallery

end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paintings }
    end
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
    @painting = Painting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/new
  # GET /paintings/new.json
  def new
    @painting = Painting.new(:gallery_id => params[:gallery_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/1/edit
  def edit
    @painting = Painting.find(params[:id])
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(params[:painting])

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render json: @painting, status: :created, location: @painting }
      else
        format.html { render action: "new" }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paintings/1
  # PUT /paintings/1.json
  def update
    @painting = Painting.find(params[:id])

    respond_to do |format|
      if @painting.update_attributes(params[:painting])
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy

    respond_to do |format|
      format.html { redirect_to gallery_url(@painting.gallery) }
      format.json { head :no_content }
    end
  end
end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/helpers/galleries_helper.rb
module GalleriesHelper
end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/helpers/paintings_helper.rb
module PaintingsHelper
end

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <%= f.hidden_field :gallery_id %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@painting.errors.count, "error")} prohibited this painting from being saved:" %>
      </h2>
      <ul>
        <% @painting.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image, 'Image URL' %>
    <%= f.url_field :image %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/views/paintings/edit.html.erb
<h1>Editing painting</h1>
<%= render 'form' %>
<%= link_to 'Show', @painting %>
|
<%= link_to 'Back', paintings_path %>

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/views/paintings/new.html.erb
<h1>New painting</h1>
<%= render 'form' %>
<%= link_to "Back to Gallery", @painting.gallery %>

resources/review topics and Exercises/file_uploads_with_carrierwave_lab/gallery_app_start/app/views/paintings/show.html.erb
<h1>
  <%= @painting.title %>
</h1>
<p>
  <b>Artist:</b>
  <%= @painting.artist %>
</p>
<p>
  <b>Description:</b>
  <%= @painting.description %>
</p>
<p>
  <b>Price:</b>
  <%= @painting.price %>
</p>
<p>
  <b>Gallery:</b>
  <%= @painting.gallery.name %>
</p>
<p>
  <%= image_tag @painting.image %>
</p>
<%= link_to 'Edit', edit_painting_path(@painting) %>
|
<%= link_to "Back to Gallery", @painting.gallery %>